# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkoutSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('reps', models.IntegerField(default=1)),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOutLogger.User')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=400)),
                ('wtype', models.CharField(max_length=100)),
                ('body_part', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userworkoutset',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOutLogger.WorkOut'),
        ),
    ]
